apiVersion: v1
kind: Namespace
metadata:
  name: scale-test-app-6
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: scale-test-app-6
  namespace: scale-test-app-6
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - scale-test-app-6
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 10k-scale-default
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: scale-test-app-6
  name: scale-test-app-6-subscription-1
  namespace: scale-test-app-6
spec:
  channel: ggithubcom-cdoan1-appsub-scale-guide-ns/ggithubcom-cdoan1-appsub-scale-guide
  placement:
    placementRef:
      kind: PlacementRule
      name: scale-test-app-6-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: scale-test-app-6
  name: scale-test-app-6-placement-1
  namespace: scale-test-app-6
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
